---
title: "305 Lecture 25 - Introducing Probability"
author: "Brian Weatherson"
date: "July 20, 2020"
output: 
  beamer_presentation:
    md_extensions: +link_attributes
    keep_tex: true
    latex_engine: xelatex
    includes:
      in_header: 305-beamer-header.tex
---

## Plan

- This lecture introduces the basics of probability.

## Basic Idea

- A probability function is a mapping from possibilities to numbers.
- The numbers must sum to one.
- Intuitively, the numbers measure how likely the possibilities are.

## Sum to One

The math of probability functions is just the math of proportions. Ultimately, all we'll be doing is the same kind of math that you would do when thinking about things like

- What proportion of UM students are from North Carolina?
- What proportion of UM undergraduates are Tigers fans?

etc.

## Three Big Questions

> 1. What to do with these numbers?
> 2. Where these numbers come from?
> 3. What do the numbers even mean?

## A Simple Case

- Imagine that it is basketball season, and UM has planned to have both the women's and men's teams play on the same night.
- So at the end of the night there are four possible outcomes.

## Made Up Probabilities

I'll stipulate that the probabilities of the four possible outcomes are given by this table.

              Men Win   Men Lose
-----------  --------- ----------
Women Win       0.45      0.25
Women Lose      0.20      0.10

## Another Representation

Here are the same numbers written a different way.

 Women   Men    Probability
------- ------ -------------
  Win    Win        0.45
  Win    Lose       0.25
  Lose   Win        0.20
  Lose   Lose       0.10
  
## Possibilities

Say a possibility (for current purposes) is one of these maximally specific things that the probability is defined over.

- It is not really a complete possibility.
- It doesn't tell us the score, or the weather, or the results of the next election, or for that matter the results of the last election.
- But it tells us everything that's relevant to a particular inquiry.
- It is a lot like a line on a truth table.
  
## Events

We will say an **event** is a proposition that can be defined using these possibilities. So here are some sample events.

- The women's team wins.
- The men's team wins.
- At least one Michigan team wins.
- The two teams have the same result.

## Probability of Events

- An event is true at some possibilities, false at others.
- Each possibility gets a probability.
- The probability of an event is the sum of the probabilities of the possibilities where it is true.

## Examples - Probability Women's Team Wins

\begincols
\begincol{.48\textwidth}

 Women   Men    Probability
------- ------ -------------
  Win    Win        0.45
  Win    Lose       0.25
  Lose   Win        0.20
  Lose   Lose       0.10
  
\endcol
\begincol{.48\textwidth}

The women's team wins at lines 1 and 2.

- So its probability is 0.45 + 0.25 = $0.7$.

\endcol
\endcols

## Examples - Probability Men's Team Wins

\begincols
\begincol{.48\textwidth}

 Women   Men    Probability
------- ------ -------------
  Win    Win        0.45
  Win    Lose       0.25
  Lose   Win        0.20
  Lose   Lose       0.10
  
\endcol
\begincol{.48\textwidth}

The men's team wins at lines 1 and 3.

- So its probability is 0.45 + 0.20 = $0.65$.

\endcol
\endcols

## Examples - At Least One Team Wins

\begincols
\begincol{.48\textwidth}

 Women   Men    Probability
------- ------ -------------
  Win    Win        0.45
  Win    Lose       0.25
  Lose   Win        0.20
  Lose   Lose       0.10
  
\endcol
\begincol{.48\textwidth}

\pause

At least one team wins at lines 1, 2 and 3.

- So its probability is 0.45 + 0.25 + 0.20 = $0.90$.

\endcol
\endcols

## Examples - Same Result in Each Game

\begincols
\begincol{.48\textwidth}

 Women   Men    Probability
------- ------ -------------
  Win    Win        0.45
  Win    Lose       0.25
  Lose   Win        0.20
  Lose   Lose       0.10
  
\endcol
\begincol{.48\textwidth}

\pause

It is the same result in each game at lines 1 and 4.

- So its probability is 0.45 + 0.10 = $0.55$.

\endcol
\endcols

## For Next Time

- We will look at some properties that all probability functions share.