---
title: "305 Lecture 63 - The Logic Of Counterfactuals"
author: "Brian Weatherson"
date: "August 10, 2020"
output: 
  beamer_presentation:
    md_extensions: +link_attributes
    keep_tex: true
    latex_engine: xelatex
    includes:
      in_header: 305-beamer-header.tex
---

## Plan

- To discuss some features of the logic of counterfactual conditionals.

## Associated Reading

- Boxes and Diamonds, chapter 7.

## Transitivity (or Conditional Syllogism)

This argument seems initially compelling for any interpretation of 'if'.

1. If $A, B$.
2. If $B, C$.
3. So if $A, C$.

## Transitivity for Subjunctives

On the nearest possible world, or minimal change, semantics, this will fail for subjunctive conditionals.

- Imagine there is no nearby world where $A$.
- The nearest $A$ worlds (which in these cases will be quite distant) are worlds where $B$ is true and $C$ is false.
- There are nearby, normal $B$ worlds, and they are all worlds where $C$ is true.

## Real Life Example

1. If there had been a hurricane and a blizzard last weekend, it would have snowed last weekend. \pause 
2. If it had snowed last weekend, Smith would have gone skiing last weekend. \pause 
3. So if there had been a hurricane and a blizzard last weekend, Smith would have gone skiing last weekend.

## Link To Antecedent Strengthening

1. If I had crashed my car last week and won the lottery on the weekend, I'd have crashed my car last week. \pause 
2. If I had crashed my car last week, I'd now have less money than actually do. \pause 
3. So if I had crashed my car last week and won the lottery on the weekend, I'd now have less money than actually do.

## Recipe Here

Assume that you have _If A, C_, but not _If A and B, C_.

1. If $A$ and $B$, $A$.
2. If $A, C$.
3. So, If $A$ and $B$, $C$.

That should have true premises and a false conclusion.

## But Wait

But don't we reason this way all the time.

1. If there had been a major earthquake in Ann Arbor last weekend, this class would have been cancelled. \pause 
2. If this class had been cancelled, I would have been disappointed. \pause 
3. So if there had been a major earthquake in Ann Arbor on the weekend, I would have been disappointed.

The point is not that 1-3 look true here, it's that reasoning from 1 and 2 to 3 looks like good, ordinary, everyday reasoning.

## Modified Transitivity

This argument form is valid on the minimal change semantics.

1. If $A, B$
2. If $A \wedge B, C$
3. So, if $A, C$

## Proof Of Modified Transitivity

- Let $d$ be the distance of the nearest $A$ world.
- By premise 1, all of those nearest $A$ worlds, which are distance $d$ away, are $B$ worlds. \pause 
- So they are also the nearest $A \wedge B$ worlds. (There can't be any closer, because then they would be closer $A$ worlds.) \pause 
- By premise 2 then, all these $A \wedge B$ worlds distance $d$ away are also $C$ worlds.
- So all the $A$ worlds distance $d$ away are $C$ worlds. \pause 
- So, if $A, C$.

## Explanation

Lewis suggested that was what was really going on when we use transitivity arguments in everyday life.

- The middle premise is really _If A and B, C_, not just _If B, C_.
- Is this plausible? I don't know.


## For Next Time

We'll end with a discussion of the notion of similarity that is used in this logic.