---
title: "305 Lecture 37 - Updating on Multiple Data Points"
author: "Brian Weatherson"
date: "July 22, 2020"
output: 
  beamer_presentation:
    md_extensions: +link_attributes
    keep_tex: true
    latex_engine: xelatex
    includes:
      in_header: 305-beamer-header.tex
---

## Plan

- We will end the week by looking at some examples of updating on multiple data points.

## Conditional Independence

In a lot of cases, the two data points we get will not be probabilistically independent, but they will be **conditionally independent**.

That is, if $B_1$ and $B_2$ are the data points, and $X$ is an arbitrary hypothesis (like $A, \neg A$), we will have

> $\Pr(B_1 | X)\Pr(B_2 | X) = \Pr(B_1 \wedge B_2 | X)$

## Biased Coins

Here is one kind of case where the happens.

- We have a bunch of biased coins. For each of them, there is a probability $p$ of heads on an arbitrary flip, but we don't know what that is. \pause
- The results of two flips of the same coin are not indepdendent.
- If one flip lands heads, that is evidence of a bias towards heads, and hence it increases the probability of heads on the next flip. \pause
- But conditional on a hypothesis about the bias of the coin, the flips are independent.

## Skilled Activity

A perhaps more real-life case of this is skilled action, like shooting free throws.

- The success of one attempt is not independent of the success of the previous.
- But conditional on the skill of the actor, the attempts are (probably, more or less) independent.

## Sampling With Replacement

Drawing from a selection **with replacement** produces conditional independence.

- If I don't know how many black marbles are in an urn, then drawing a black marble **and replacing it** will be evidence that the next marble is black.
- But conditional on a hypothesis about the nature of the urn, the draws with replacement will be independent.

## Yesterday, Today, Tomorrow

This is a little off topic, but a lot of real world phenomena satisfy (roughly) the following condition.

- How things were yesterday is a good (probabilistic) guide to how things will be tomorrow.
- So how things will be tomorrow is not independent of how things were yesterday. \pause
- But, conditional on how things are today, how things were yesterday and will be tomorrow are independent.
- Knowing how things were yesterday doesn't tell you any more about how things will be tomorrow once you know how things are today.

## Markov Chains

A chain of events where every event is probabilistically dependent on the previous one, but only on the previous one, is called a **Markov Chain**. \pause

- Lots of real world processes are (more or less) Markov Chains.
- Weather systems, for instance, are probably more or less Markov Chains.
- And lots of ecological models assume that animal populations are Markov Chains.
- And the core idea is just conditional independence.

## Conditional Independence

In cases where the data points $B_1$ and $B_2$ are independent, we have an easy story about how to work out the probabilities.

> $\Pr(B_1 \wedge B_2 | X) = \Pr(B_1 | X)\Pr(B_2 | X)$

## Same Event

There is an even simpler formula where $B_1$ and $B_2$ are the 'same' event, like the coin landing heads both time, or the same color marble being drawn. 

> $\Pr(B_1 \wedge B_2 | X) = \Pr(B_1 | X)^2$

## An Example

There are two urns in front of us.

- One of them - urn A - has 4 red marbles, 3 green marbles, and 3 blue marbles.
- The other - urn B- has 8 red marbles, 1 green marbles and 1 blue marbles. \pause

One of the urns will be selected at random, and then a marble drawn from it.

- If the marble is red, what is the probability that Urn A was selected?

## A Table

I'll just do the column for red marble selected.

|           |        Red             |
|:---------:|:----------------------:|
| Urn A     | $0.5 \times 0.4 = 0.2$ |
| Urn B     | $0.5 \times 0.8 = 0.4$ |
| **Total** | $0.2 + 0.4 = 0.6$      |

\pause

$$
\Pr(A | Red) = \frac{\Pr(A \wedge Red)}{\Pr(Red)} = \frac{0.2}{0.6} = \frac{1}{3}
$$

## Another Example

There are two urns in front of us.

- One of them - urn A - has 4 red marbles, 3 green marbles, and 3 blue marbles.
- The other - urn B- has 8 red marbles, 1 green marbles and 1 blue marbles. \pause

One of the urns will be selected at random, and then two marbles drawn from it **with replacement**.

- If both draws are red, what is the probability that Urn A was selected?

## A Table

|           |        Red-Red            |
|:---------:|:-------------------------:|
| Urn A     | $0.5 \times 0.4^2 = 0.08$ |
| Urn B     | $0.5 \times 0.8^2 = 0.32$ |
| **Total** | $0.08 + 0.32 = 0.4$       |

\pause

$$
\Pr(A | Red-Red) = \frac{\Pr(A \wedge Red-Red)}{\Pr(Red-Red)} = \frac{0.08}{0.4} = \frac{1}{5}
$$

The probability of Urn A fell by a lot.

## Yet Another Example

There are two urns in front of us.

- One of them - urn A - has 4 red marbles, 3 green marbles, and 3 blue marbles.
- The other - urn B- has 8 red marbles, 1 green marbles and 1 blue marbles. \pause

One of the urns will be selected at random, and then two marbles drawn from it **with replacement**.

- If the first draw is red and the second green, what is the probability that Urn A was selected?

## A Table

|           |       Red-Green                     |
|:---------:|:-----------------------------------:|
| Urn A     | $0.5 \times 0.4 \times 0.3 = 0.06$  |
| Urn B     | $0.5 \times 0.8 \times 0.1 = 0.04$  |
| **Total** | $0.06 + 0.04 = 0.1$                 |

\pause

$$
\Pr(A | Red-Green) = \frac{\Pr(A \wedge Red-Green)}{\Pr(Red-Green)} = \frac{0.06}{0.1} = \frac{3}{5}
$$

The probability of Urn A rose by a lot.

# Dependent Events

## Dependence

What happens if the events $B_1$ and $B_2$ are dependent on one or other of the hypotheses?

- The typical case is that they will be dependent on none or all of the hypotheses.
- But it's possible in principle to have independence on some and dependence on others. 
- And in that case we have to use the more complicated procedure I'm about to describe.

## Sampling Without Replacement

The paradigm example of conditional dependence is sampling **without replacement**.

- Assume you know which urn I'm using.
- Then the draws without replacement won't be independent because every time you draw a marble, there are fewer marbles of that color to draw the next time.

## Example

Assume that I am using urn A. (Or assume that we are working out conditional probabilities conditional on urn A.)

- For the first draw, the probability of red is 4 in 10, or  0.4.
- Conditional on the first draw being red, the probability of the second draw being red is 3 in 9, or $\frac{1}{3}$.
- That's because there are now 9 marbles left, and 3 of them are red.

## Continuing the Example

So to work out the probability of some sequence of draws $D_1, D_2$ given a hypothesis $X$ about the urn, we need to use the more complicated rule.

$$
\Pr(D_1 \wedge D_2 | X) = \Pr(D_1 | X) \Pr(D_2 | X \wedge D_1)
$$

\pause
For example

$$
\Pr(Red_1 \wedge Red_2 | A) = \Pr(Red_1 | A)\Pr(Red_2 | A \wedge Red_1) = \frac{4}{10} \times \frac{3}{9} = \frac{2}{15}
$$

## Continuing the Example

So to work out the probability of some sequence of draws $D_1, D_2$ given a hypothesis $X$ about the urn, we need to use the more complicated rule.

$$
\Pr(D_1 \wedge D_2 | X) = \Pr(D_1 | X) \Pr(D_2 | X \wedge D_1)
$$

For example

$$
\Pr(Red_1 \wedge Red_2 | B) = \Pr(Red_1 | B)\Pr(Red_2 | B \wedge Red_1) = \frac{8}{10} \times \frac{7}{9} = \frac{28}{45}
$$

## Another Example

There are two urns in front of us.

- One of them - urn A - has 4 red marbles, 3 green marbles, and 3 blue marbles.
- The other - urn B- has 8 red marbles, 1 green marbles and 1 blue marbles. \pause

One of the urns will be selected at random, and then two marbles drawn from it **without replacement**.

- If both draws are red, what is the probability that Urn A was selected?

## A Table

|           |        Red-Red                                               |
|:---------:|:------------------------------------------------------------:|
| Urn A     | $0.5 \times \frac{4}{10} \times \frac{3}{9} = \frac{1}{15}$  |
| Urn B     | $0.5 \times \frac{8}{10} \times \frac{7}{9} = \frac{14}{45}$ |
| **Total** | $\frac{1}{15} + \frac{14}{45} = \frac{17}{45}$               |

\pause

$$
\Pr(A | Red-Red) = \frac{\Pr(A \wedge Red-Red)}{\Pr(Red-Red)} = \frac{\frac{1}{15}}{\frac{17}{45}} = \frac{3}{17}
$$

The probability of Urn A fell by a bit more.

## Yet Another Example

There are two urns in front of us.

- One of them - urn A - has 4 red marbles, 3 green marbles, and 3 blue marbles.
- The other - urn B- has 8 red marbles, 1 green marbles and 1 blue marbles. \pause

One of the urns will be selected at random, and then two marbles drawn from it **with replacement**.

- If the first draw is red and the second green, what is the probability that Urn A was selected?

## The General Conjunction Rule

To work out the probability of some sequence of draws $D_1, D_2$ given a hypothesis $X$ about the urn, we need to use the more complicated rule.

$$
\Pr(D_1 \wedge D_2 | X) = \Pr(D_1 | X) \Pr(D_2 | X \wedge D_1)
$$

\pause
So in this case we get

$$
\Pr(Red_1 \wedge Green_2 | A) = \Pr(Red_1 | A)\Pr(Green_2 | A \wedge Red_1) = \frac{4}{10} \times \frac{3}{9} = \frac{2}{15}
$$

## The General Conjunction Rule

To work out the probability of some sequence of draws $D_1, D_2$ given a hypothesis $X$ about the urn, we need to use the more complicated rule.

$$
\Pr(D_1 \wedge D_2 | X) = \Pr(D_1 | X) \Pr(D_2 | X \wedge D_1)
$$

And for Urn B we get

$$
\Pr(Red_1 \wedge Green_2 | B) = \Pr(Red_1 | B)\Pr(Green_2 | B \wedge Red_1) = \frac{8}{10} \times \frac{1}{9} = \frac{4}{45}
$$

## A Table

|           |        Red-Green                                             |
|:---------:|:------------------------------------------------------------:|
| Urn A     | $0.5 \times \frac{4}{10} \times \frac{3}{9} = \frac{1}{15}$  |
| Urn B     | $0.5 \times \frac{8}{10} \times \frac{1}{9} = \frac{2}{45}$  |
| **Total** | $\frac{1}{15} + \frac{2}{45} = \frac{5}{45}$                 |

\pause

$$
\Pr(A | Red-Green) = \frac{\Pr(A \wedge Red-Red)}{\Pr(Red-Red)} = \frac{\frac{1}{15}}{\frac{5}{45}} = \frac{3}{5}
$$

Which, interestingly, is exactly the same as in the with replacement case.

## Last (Difficult) Example

- There are four urns in the room, three of type X, one of type Y.
- The type X urns have 4 blue marbles and 2 yellow marbles.
- The type Y urn has 5 blue marbles and 3 yellow marbles.
- One of the four urns was selected at random.
- Then two marbles were selected **without replacement** from the randomly selected urn.
- The first was blue, the second was yellow.
- A third marble is about to be selected.
- What is the probability that it is blue?

## The Table

|   Urn     |    Blue-then-Yellow                                               |
|:---------:|:-----------------------------------------------------------------:|
| Type X    | $\frac{3}{4} \times \frac{4}{6} \times \frac{2}{5} = \frac{1}{5}$ |
| Type Y    |                                                                   |
| **Total** |                                                                   |

$$
\Pr(X \wedge Blue_1 \wedge Yellow_2) = \Pr(X) \times \Pr(Blue_1 | X) \times \Pr(Yellow_2 | X \wedge Blue_1)
$$

## The Table

|   Urn     |    Blue-then-Yellow                                                  |
|:---------:|:--------------------------------------------------------------------:|
| Type X    | $\frac{3}{4} \times \frac{4}{6} \times \frac{2}{5} = \frac{1}{5}$    |
| Type Y    | $\frac{1}{4} \times \frac{5}{8} \times \frac{3}{7} = \frac{15}{224}$ |
| **Total** |                                                                      |

$$
\Pr(Y \wedge Blue_1 \wedge Yellow_2) = \Pr(Y) \times \Pr(Blue_1 | Y) \times \Pr(Yellow_2 | Y \wedge Blue_1)
$$

## The Table

|   Urn     |  Blue-then-Yellow  |
|:---------:|:------------------:|
| Type X    | $\frac{1}{5}$      |
| Type Y    | $\frac{15}{224}$   |
| **Total** | $\frac{299}{1120}$ |                                                 |

You should double check this, but I think

$$
\frac{1}{5} + \frac{15}{224} = \frac{299}{1120}
$$

So that's $\Pr(Blue_1 \wedge Yellow_2)$

## Conditional Probabilities

$$
\Pr(X | Blue_1 \wedge Yellow_2) = \frac{\Pr(X \wedge Blue_1 \wedge Yellow_2)}{\Pr(Blue_1 \wedge Yellow_2)} = \frac{\frac{1}{5}}{\frac{299}{1120}} = \frac{224}{299}
$$

$$
\Pr(Y | Blue_1 \wedge Yellow_2) = \frac{\Pr(Y \wedge Blue_1 \wedge Yellow_2)}{\Pr(Blue_1 \wedge Yellow_2)} = \frac{\frac{15}{224}}{\frac{299}{1120}} = \frac{75}{299}
$$
The probability of Y is ever so fractionally higher than when we started.

## Next Marble

- If X (and Blue-followed-by-Yellow), the probability of next marble being blue is $\frac{3}{4}$.
- If Y (and Blue-followed-by-Yellow), the probability of next marble being blue is $\frac{2}{3}$. \pause
- So overall probability of next marble being blue is

$$
 \frac{224}{299} \times \frac{3}{4} + \frac{75}{299} \times \frac{2}{3} = \frac{218}{299} \approx 0.729
$$

## General Strategy of Last Slide

- If there are two hypotheses X and Y, and you want to know the probability of some event E, it will be given by

$$
\Pr(E) = \Pr(X)\Pr(E | X) + \Pr(Y)\Pr(E | Y)
$$

And that generalises to the case where there are multiple hypotheses $H_1, \dots H_n$

$$
\Pr(E) = \Pr(H_1)\Pr(E | H_1) + \dots +  \Pr(H_n)\Pr(E | H_n)
$$

## For Next Time

Next week we will look at the use of probability in decision making, and in science.