---
title: "305 Lecture 02 - The Nature of Logic"
author: "Brian Weatherson"
date: "July 1, 2020"
output: 
  beamer_presentation:
    md_extensions: +link_attributes
    keep_tex: true
    latex_engine: xelatex
    includes:
      in_header: 305-beamer-header.tex
---

## Plan for This Lecture

We're discussing the nature of arguments, and in particular, the role of premises and conclusions.

## Associated Reading

Carnap book, chapter 1, section "Arguments and Reasoning".

## Arguments

Logic studies certain properties of arguments.

An argument, in the sense we're interested in, has two parts:

1. Premises
2. Conclusion

## Example

``
\DisplayArg{
\item All kangaroos are wise.
\item Skippy is a kangaroo.
}
{
Skippy is wise.
}
``{=latex} 

## Premises

``
\DisplayArg{
\item All kangaroos are wise.
\item Skippy is a kangaroo.
}
{
Skippy is wise.
}
``{=latex} 

The **premises** go above the line, and are numbered.

## Conclusion

``
\DisplayArg{
\item All kangaroos are wise.
\item Skippy is a kangaroo.
}
{
Skippy is wise.
}
``{=latex} 

The **conclusion** goes below the line, and is not numbered.

## The Premise Set

``
\DisplayArg{
\item All kangaroos are wise.
\item Skippy is a kangaroo.
}
{
Skippy is wise.
}
``{=latex} 

There can be zero, one or multiple premises. Formally, we'll say there is a set of premises.

## Zero Premises

``
\hrulefill
\begin{quote}
{\normalfont All men are created equal.}
\end{quote}
\vspace{12pt}
``{=latex} 

## One Premise

``
\DisplayArg{
\item The cinema is closed.
}
{
We shouldn't go to the cinema.
}
``{=latex} 

## Conclusion

``
\DisplayArg{
\item All kangaroos are wise.
\item Skippy is a kangaroo.
}
{
Skippy is wise.
}
``{=latex} 

But we don't allow this flexibility to conclusions; arguments have a single conclusion.

## Chained Arguments

- Sometimes a conclusion of one argument will go to be a premise in another argument.
- But any given argument aims to prove just one thing.

## Representation

``
\DisplayArg{
\item All kangaroos are wise.
\item Skippy is a kangaroo.
}
{
Skippy is wise.
}
``{=latex} 

When I write arguments like this, I'm merely presenting them, not asserting that they have any nice features.

## Virtues of Arguments

What are some virtues of arguments that you can think of? What makes for a good argument?

## Virtues of Arguments

> - Premises are true.
> - Premises are known. 
> - Premises are accepted in debate. 
> - Premises are evidence for the conclusion.
> - Premises guarantee the truth of the conclusion.

## Logic

To a first approximation, logic is about the last of these virtues.

- Does the truth of a set of premises **guarantee** the truth of the conclusion?

## Structure

Logic isn't just about guarantees though. It's about a special kind of guarantee, one that holds in virtue of the structure of the premises and conclusion.

## Non-Structural Guarantee

Compare the Skippy argument with this one.

``
\DisplayArg{
\item Today is Wednesday.
}
{
Tomorrow is Thursday.
}
``{=latex}

The premise guarantees the truth of the conclusion, but it does so in virtue of meanings of 'Wednesday' and 'Thursday', not structural features.

## Structure and Substitution

When the structure of the argument does the guaranteeing, the guarantee would persist through some substitutions.

``
\DisplayArg{
\item All kangaroos are wise.
\item Skippy is a kangaroo.
}
{
Skippy is wise.
}
``{=latex}

## Structure and Substitution

When the structure of the argument does the guaranteeing, the guarantee would persist through some substitutions.

``
\DisplayArg{
\item All kangaroos are wise.
\item Lucky is a kangaroo.
}
{
Lucky is wise.
}
``{=latex}

## Structure and Substitution

When the structure of the argument does the guaranteeing, the guarantee would persist through some substitutions.

``
\DisplayArg{
\item All koalas are wise.
\item Lucky is a koala.
}
{
Lucky is wise.
}
``{=latex}

## Structure and Substitution

When the structure of the argument does the guaranteeing, the guarantee would persist through some substitutions.

``
\DisplayArg{
\item All koalas are dishonest.
\item Lucky is a koala.
}
{
Lucky is dishonest.
}
``{=latex}

## Terminology

- We'll say an argument is **valid** just in case the truth of the premises guarantees the truth of the conclusion.
- We'll say an argument is **sound** just in case it is valid and has true premises.
- We won't have much interest here in soundness; just in validity.

## Validity

Here are some equivalent ways to define validity.

- An argument is valid if necessarily, when the premises are true, the conclusion is too.
- An argument is valid if it is impossible for the premises to be true and the conclusion to not be true.

We'll use that last formulation a lot.

## For Next Time

We'll look at the most fundamental kind of logic: propositional logic.
