---
title: "305 Lecture 27 - About Probability Functions"
author: "Brian Weatherson"
date: "July 20, 2020"
output: 
  beamer_presentation:
    md_extensions: +link_attributes
    keep_tex: true
    latex_engine: xelatex
    includes:
      in_header: 305-beamer-header.tex
---

## Plan

- This lecture looks at some general features of probability functions, and looks at some ways to think probabilistically about real world events.

## Associated Reading

Odds and Ends, Chapter 5

## Scale

$$
0 \leq \Pr(A) \leq 1
$$

## Negation

$$
\Pr(\neg A) = 1 - \Pr(A)
$$

## Excluded Middle

$$
\Pr(A) + \Pr(\neg A) = 1
$$

## Partition

Some events $A_1, \dots A_n$ form a partition if, necessarily, exactly one of them is true.

- So they are **exclusive** - you can't have any two of them both be true.
- And they are **exhaustive** - you have to have at least one true.

## Partition

If $A_1, \dots A_n$ form a partition then

$$
\Pr(A_1) + \dots + \Pr(A_n) = 1
$$

## Exclusive

If $A, B$ are exclusive

$$
\Pr(A \vee B) = \Pr(A) + \Pr(B)
$$

## General Principle

$$
\Pr(A) + \Pr(B) = \Pr(A \vee B) + \Pr(A \wedge B)
$$

\pause

It's worth thinking through why this is true in terms of possibilities.

## Trees

- Often, we can't just write down numbers for the possibilities.
- But we can write down, or at least make reasonable guesses about, numbers for certain events.
- And we can think about how things are likely to go given those events happen.
- This is the tree structure that is used in _Odds and Ends_.

## Academic Forecasting

- So let's say you're interested in the probability that we have in person classes all the way through Fall semester.
- It looks like we're going to start with in person classes (at least for some classes), and the virus numbers are falling quickly in Michigan, so maybe this will all work out.
- Respiratory viruses do tend to get worse in the Fall, so things could get bad in November. 
- But the vaccine trials are going better than I expected at this point, and that surely matters.
- But it's hard to put into numbers how it affects things.

## One Method

- Divide up the state space.
- Work out the probability of being in one or other part of the space.
- Work out the probability of classes running all semester in each part of the space.
- Add things up.

## Nothing is Reliable

> - There are a lot of ways to do this.
> - You could divide up the space by how many cases there are in Michigan.
> - Or you could divide up the space by how many other universities shut down.
> - Or, and let's work with this one, you could divide it up by whether there is a vaccine that's known to work by October.

## Three States

1. No vaccine.
2. Limited quantities of vaccine.
3. Readily available vaccine.

## Two Step Process

1. Work out (or at least estimate) probability of each state.
2. Work out probability of Trump winning within each of those states.

This will involve a lot of guesswork - do not make investment decisions on the basis of the numbers I'm about to use because they are really pulled out of the air - but it's a very helpful heuristic to at least approximate the reality.

## Probabilities of States

This could be embarrassingly out of date by the time we even do the classes, but let's say the probabilities look like this.

- No vaccine - 70%, or 0.7.
- Limited quantities of vaccine - 20%, or 0.2.
- Unlimited quantities of vaccine - 10%, or 0.1

## Class Probabilities

Then we want to work out how likely it is that we get a full semester of classes in given each of these three possibilities.

## No Vaccine

If there's no vaccine, then all that matters is whether we think there will be enough cases in the Fall to cause the university to shut down again. Even with masks, distancing, etc, it's hard to avoid outbreaks on places like college campuses. But maybe we'll be able to isolate anyone who gets sick, so let's be a litle optimistic and say that even without a vaccine, we're 60% likely to get through the semester.

> - I really want to emphasise that I'm making these numbers up for the purposes of an in class example. I have no special insight into either the university's thinking, or epidemiology. If you have any reason to think they are wrong, in either direction, do not change your views on my account.

## Limited Vaccine

This starts to feel more like something where we can get through the term. Would the university risk running classes if it could give vaccines to the old professors and could hope and pray that young people (i.e., students) will only get a bit sick? Or would even a limited vaccine mean that infections wouldn't spread? Maybe!

- But even still, things could go wrong. So let's say there is a 20% chance of a shut down even with a limited vaccine, and so an 80% chance of the semester going ahead.

## Unlimited vaccine

Now it's hard to see why the university would shut down. Rather than fuss about the details, let's just simplify and say that in this (very unlikely) scenario, it's 100% likely that we'll get all classes in.


## The Giant Table

                                     Full Semester             Some shutdown
---------------------------- ------------------------- -------------------------
No vaccine                    $0.7 \times 0.6 = 0.42$   $0.7 \times 0.4 = 0.28$
Limited vaccine               $0.2 \times 0.8 = 0.16$   $0.2 \times 0.2 = 0.04$
Unlimited vaccine             $0.1 \times 1.0 = 0.10$   $0.1 \times 0.0 = 0.00$
  
So the probability that we get a full semester in (given these literally made up assumptions) is $0.42 + 0.16 + 0.1 = 0.68$, or 68%.

## Probabilities and Errors

- The error bars on that calculation are massive.
- But it's a kind of sanity check on how you think things are going.
- Especially in situations where only a handful of paths lead to a salient result (like in playoffs in sports, or when thinking about the likelihood of a particular challenger winning), doing the tree even with favorable numbers can give you a conservative estimate of some probability.

## Three Cases Where This is More Precise

1. Probabilities are stipulated
2. Probabilities are due to well understood chance processes (like gambling devices)
3. Probabilities are derived from very large data sets

## For Next Time

- We will look at an example where the probabilities are indeed stipulated.