---
title: "305 Lecture 03 - Propositional Logic"
author: "Brian Weatherson"
date: "July 1, 2020"
output: 
  beamer_presentation:
    md_extensions: +link_attributes
    keep_tex: true
    latex_engine: xelatex
    includes:
      in_header: 305-beamer-header.tex
---

## Plan for This Lecture

We're introducing propositional logic, and talking about what it is.

## Associated Reading

Carnap book, chapter 1, section "Our Formal Language".

## Key Assumption

We start with one key assumption:

- Every sentence has precisely one of the two truth values: TRUE, FALSE.
- I will often follow _Boxes and Diamonds_ as writing these values as $\True$ and $\False$.

## Unpacking the Assumption

1. There are just two truth values: $\True$, $\False$.  
2. Every sentence has one of them. There are no truth-value *gaps*. 
3. No sentence has both of them. There are no truth-value *gluts*.

## Two Parts of Classical Logic

- Traditionally, classical logic is divided into two parts. 
- We're just going to look at the first part here.
- The parts differ on what counts as a **structural** feature of a sentence.

## Classical Propositional Logic

The structural features are just five sentential connectives:

- And
- Or
- Not
- If
- If and only if; usually written iff.

The result is a very simple, but very weak, logic. It doesn't even tell us that the arguments about Skippy and Lucky are structurally valid.

## Classical Predicate Logic

As well as those structural features, we add:

- The division of parts of sentences into names, variables, predicates, and logical terms.
- The addition of the logical terms **All** and **Some**.

## Symbols

The only symbols we need for classical propositional logic are sentence letters, which stand for sentences, and symbols for the five connectives:

- And - $\wedge$
- Or - $\vee$
- Not - $\neg$
- If - $\lif$
- Iff - $\leftrightarrow$

## Examples

If $A$ = _Lucky is a koala_ and $B$ = _Skippy is a kangaroo_, then

> - $\neg A$ = _Lucky is not a koala_.
> - $A \vee B$ = _Lucky is a koala or Skippy is a kangaroo_.
> - $\neg B \wedge A$ = _Skippy is not a kangaroo and Lucky is a koala_.
> - $(A \vee B) \lif (A \wedge B)$ = _If Lucky is a koala or Skippy is a kangaroo, then Lucky is a koala and Skippy is a kangaroo_.

## For Next Time

- Read chapters 1 and 3 of _The Carnap Book_.
- Go to http://carnap.io and register for this course
- The course name is "University of Michigan - S20 - PHIL305"